Sprint 2
Melekh11/middle.messenger.praktikum.yandex pull request #2
Opened 2022-07-18 16:45 UTC by Melekh11

Sprint 2

2022-07-19 19:06 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу)
Есть несколько замечаний:
1. Использование ts-ignore не является хорошей практикой, также как и тип any, теряются преимущества типизирования
3. Поехало форматирование, ошибки eof, для удобства можно добавить prettier в проект  https://prettier.io/docs/en/install.html
4. Неинформативные логи и закомментированный код лучше удалить
5. Не увидела класс HTTPTransport, который требуется по заданию
6. Не получилось посмотреть страницы входа и регистрации, не нашла как на них попасть, было бы супер, если для этого задания сделаешь страницу с ссылками на все страницы

2022-07-19 19:06 UTC, podlovchenko commented on src/components/input/input.ts
> +            // }
Закомментированный код лучше не оставлять в проекте, увеличивает размер файла и ухудшает читабельность

2022-07-19 19:06 UTC, podlovchenko commented on src/components/input/input.ts
> +            console.log(101);
Не очень информативный лог)

2022-07-19 19:06 UTC, podlovchenko commented on src/components/submit-button/submit-button.less
> +form button.prime{
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-07-19 19:06 UTC, podlovchenko commented on src/components/submit-button/submit-button.ts
> +                    const pAll = form.querySelectorAll(".input-error");
Лучше давать переменным говорящие названия
По названию pAll непонятно, что в ней лежит

2022-07-19 19:06 UTC, podlovchenko commented on src/helpers/handlerError.ts
> +    } return {error: false, errorText: ""};
Для такого кейса хорошо подойдет оператор switch

2022-07-19 19:06 UTC, podlovchenko commented on src/utils/core/Block.ts
> +    _registerEvents(eventBus) {
Не хватает модификатора private для приватных методов, чтобы не было доступа извне

2022-07-19 19:06 UTC, podlovchenko commented on src/pages/chats/chats.ts
> +    constructor(props) {
Почему не определен тип для props?

2022-07-19 19:06 UTC, podlovchenko commented on src/utils/core/Block.ts
> +    protected props;
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-07-19 19:06 UTC, podlovchenko commented on src/utils/core/EventBus.ts
> +    protected listeners: object;
Есть дженерик Record
`Record<string, Function[]>`

2022-07-19 19:06 UTC, podlovchenko commented on tsconfig.json
> +}
Не хватает по заданию 
```
"noImplicitAny": true,

"noUnusedLocals": true,

"noUnusedParameters": true,

"sourceMap": true,

"strictNullChecks": true
```

2022-07-19 20:31 UTC, Melekh11 commented on src/utils/core/Block.ts
> +    _registerEvents(eventBus) {
но у нас же есть Proxy

2022-07-19 20:31 UTC, Melekh11 commented on src/components/submit-button/submit-button.less
> +form button.prime{
спасибо за статью :))

2022-07-19 20:31 UTC, Melekh11 commented on src/components/input/input.ts
> +            console.log(101);
упс..

2022-07-20 10:33 UTC, podlovchenko commented
Привет, сейчас при запуске через `npm run start` белый экран
На нетлифае старая версия

2022-07-20 12:59 UTC, podlovchenko requested changes
По работе приложения все ок, но очень много ts-ignore в коде, не могу пока принять работу, попробуй максимально избавиться от ts-ignore указав корректные типы)

2022-07-20 12:59 UTC, podlovchenko commented on src/utils/core/HTTPTransport.ts
> +  return ans;
В таком кейсе можно использовать метод reduce для Object.key(data)

2022-07-20 12:59 UTC, podlovchenko commented on src/utils/core/HTTPTransport.ts
> +enum METHODS {
Enum именуется обычно в CamelCase

2022-07-20 12:59 UTC, podlovchenko commented on src/utils/core/HTTPTransport.ts
> +  get(url: string, options = {}) {
Не хватает типа для options

2022-07-20 12:59 UTC, podlovchenko commented on src/utils/core/HTTPTransport.ts
> +  request(url: string, options: Record<string, any>) {
В options нельзя передавать что угодно, стоит указать, что там может быть data, method, headers

2022-07-20 12:59 UTC, podlovchenko commented on src/utils/core/render.ts
> +  if (element.firstChild) {
Без ts-ignore
```suggestion
  if (element?.firstChild) {
```

2022-07-20 21:41 UTC, Melekh11 commented
привет, если ещё будут какие-то недочёты, пожалуйста, напиши их все в следующем комментарии к ревью, мне это очень важно, сдать работу нужно до 23:59 21-го числа(сегодня)
спасибо за понимание :))

2022-07-21 06:53 UTC, podlovchenko approved these changes
Привет, в целом все хорошо, оставила несколько замечаний, поправь их перед началом следующего спринта, работу принимаю)

2022-07-21 06:53 UTC, podlovchenko commented on src/components/input/input.ts
> +                if (!content.value) {
Можно скоратить
`if (!content?.value) {`

2022-07-21 06:53 UTC, podlovchenko commented on src/components/input/input.ts
> +                    const p = this._element.querySelector("p");
Что такое  `p`? Если это блок ошибки, то лучше назвать переменную errorBlock

2022-07-21 06:53 UTC, podlovchenko commented on src/utils/core/HTTPTransport.ts
> +enum methods {
Methods

2022-07-21 06:53 UTC, podlovchenko commented on src/pages/chats/chats.ts
> +      const stub = (fragment as any).content.querySelector(`[data-id="${child.id}"]`);
Приведение к any это такой же хак как и ts-ignore

2022-07-21 17:20 UTC, merged