sprint-3
Melekh11/middle.messenger.praktikum.yandex pull request #4
Opened 2022-08-09 17:37 UTC by Melekh11

Sprint 3

2022-08-09 18:16 UTC, podlovchenko requested changes
Привет, есть несколько замечаний

1. Страницу со всеми ссылками уже можно убрать, нужно открывать страницу входа, если пользователь не авторизован, и страницу чатов, если авторизован
2. Не получается создать чат, например, при вводе собеседника "test" ответ с бекенда приходит, но чат создать не получается
3. При обновлении страницы `Cannot GET /sing-in`
4. Добавить типы вместо any
5. Привести в порядок код (поправить ошибки EOF, отступы, убрать закомментированный код, лишние строки), здесь может помочь [prettier](https://prettier.io/docs/en/install.html)

Жду правок)

2022-08-09 18:16 UTC, podlovchenko commented on package.json
> +    "querystring-es3": "^0.2.1",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-09 18:16 UTC, podlovchenko commented on src/api/auth-api.ts
> +export default new AuthAPI()
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-08-09 18:16 UTC, podlovchenko commented on package.json
> +    "test": "parcel src/utils/test/test.html --port 5000"
Было бы здорово добавить команды для линтеров

2022-08-09 18:16 UTC, podlovchenko commented on src/api/auth-api.ts
> +// import HTTPTransport from "../utils/core/HTTPTransport";
Закомментированный код лучше не оставлять в проекте

2022-08-09 18:16 UTC, podlovchenko commented on src/api/base-api.ts
> +    put(endpoint: string, options?: Record<any, any>) {
Почему не определен тип для  options?

2022-08-09 18:16 UTC, podlovchenko commented on src/api/user-api.ts
> +    "phone": string
Зачем кавычки?

2022-08-09 18:16 UTC, podlovchenko commented on src/api/user-api.ts
> +            data: JSON.stringify(data)
JSON.stringify лучше внести внутрь HTTPTransport

2022-08-09 18:16 UTC, podlovchenko commented on src/api/user-api.ts
> +            headers: {},
Зачем передавать пустой объект?

2022-08-09 18:16 UTC, podlovchenko commented on src/utils/core/Block.ts
> +    public props: TProps;
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-08-09 18:16 UTC, podlovchenko commented on src/utils/core/Block.ts
> +    _registerEvents(eventBus: EventBus) {
Для приватных методов не хватаем модификатора private

2022-08-09 18:16 UTC, podlovchenko commented on src/utils/core/HOC.ts
> +export default connect;
В проекте во многих файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-09 21:19 UTC, Melekh11 commented
привет, не совсем понял про 2-й пункт, пользователя с логином "test" нету, потому чат не создаётся, ты о том что чат должен быть создан даже с неверным пользователем или о том что нет всплывающего "такого логина нет"  ?

2022-08-09 21:54 UTC, Melekh11 commented on src/api/user-api.ts
> +            headers: {},
а иначе будут дефолтные заголовки, которые для работы с формой не годятся

2022-08-09 21:55 UTC, Melekh11 commented on src/api/auth-api.ts
> +export default new AuthAPI()
спасибо за статью, переделаю

2022-08-09 22:06 UTC, Melekh11 commented on src/api/user-api.ts
> +            data: JSON.stringify(data)
тут всё портят те запросы, когда нужны данные формы и `JSON.stringify` не нужен, это конечно можно как-нибудь проверить, но тогда , как мне кажется, получится только сложнее

2022-08-10 04:37 UTC, podlovchenko commented on src/api/user-api.ts
> +            headers: {},
Можно в зависимости от типа данный переданных в data проставлять заголовки

2022-08-10 04:42 UTC, podlovchenko commented
При вводе test с бекенда приходил ответ со списком пользователей, такой пользователь точно есть, пробовала и на других тестовых

Сейчас не могу показать, потому что не могу попасть на страницу чатов, при входе и при новой регистрации `User already in system`

2022-08-10 09:30 UTC, Melekh11 commented
на счёт `user already in system` понял, попытаюсь поправить.  
юзера с логином "test" через сваггер не нашёл, буду просто добавлять первого из списка

2022-08-10 22:18 UTC, Melekh11 commented
поправил обновления, добавил prettier, сделал Block дженериком, пользователь с логином "test" добавляется, страницу hello page убрал + мелкие доработки

2022-08-11 09:02 UTC, podlovchenko commented
Привет, сейчас не получается войти в систему, вижу по запросам, что авторизация проходит и приходят данные пользователя, но редиректа на страницу чатов нет

2022-08-11 21:19 UTC, Melekh11 commented
оказалась ошибка в обновлении `Store`
+ добавил редирект в netlify

2022-08-12 13:57 UTC, podlovchenko commented
Запрос на авторизацию проходит, а на получение пользователя нет
<img width="808" alt="Снимок экрана 2022-08-12 в 15 49 42" src="https://user-images.githubusercontent.com/22602747/184368504-8c476a3c-d093-4868-ac1e-d4facbb9f9c1.png">
Куки чистила

2022-08-12 15:43 UTC, podlovchenko commented
При перезагрузке страницы все равно открывается страница авторизации на нетлифае, если пользователь в системе

2022-08-12 22:03 UTC, Melekh11 commented
теперь при перезагрузке пользователя либо направляет на страницу чатов, либо на страницу логина  
обновление страницы чатов не выбрасывает ошибку и не выкидывает пользователя из системы

2022-08-13 09:05 UTC, podlovchenko commented
По заданию
<img width="791" alt="Снимок экрана 2022-08-13 в 12 02 32" src="https://user-images.githubusercontent.com/22602747/184476908-9126f703-5c63-4afc-8c33-d7aacdd7c3de.png">
Например, путь /profile, при перезагрузке страницы, если пользователь в системе, то он должен остаться на этой странице, если не авторизован, то редирект на страницу входа
Если путь /, то если авторизован, то переходим на страницу чатов, если нет, то страница входа

2022-08-13 09:06 UTC, podlovchenko commented
Если пользователь не авторизован, то при перезагрузке страницы регистрации должен остаться на ней

2022-08-13 20:01 UTC, Melekh11 commented
поправил

2022-08-14 14:47 UTC, podlovchenko commented
История чатов не сохраняется при переходе между чатами и при перезагрузке страницы

2022-08-14 14:48 UTC, podlovchenko commented
Прежде чем сдавать работу в следующий раз пройдись, пожалуйста, по всем пунктам чек листа и проверь работоспособность приложения

2022-08-14 15:59 UTC, Melekh11 commented
я думал обязательны только "Основные задания"

2022-08-14 16:25 UTC, Melekh11 commented
может у меня чеклист не тот, но я там не нашёл ничего про сохранения чатов после перезагрузки, скинь где ты это прочитала

я перечитал
1. Основные задания
2. [чеклист 3 спринта](https://code.s3.yandex.net/frontend-developer/middle%20frontend/3%20sprint/index3spr.html)  
3. ТЗ в начале курса
нигде про сохранения истории чатов не нашёл

2022-08-15 06:50 UTC, podlovchenko commented
Привет, есть пункты `Подключена отправка сообщений` и `Подключите WebSocket для работы с real-time сообщениями`
Кажется, что вполне логично, что приложение мессенжер должно подтягивать историю переписки
Но я согласна, в задании явно не указано про сохранение истории чатов, я уточню у кураторов могу ли я принять работу

2022-08-15 08:16 UTC, podlovchenko commented
Работу могу сейчас принять, отправь ее еще раз на проверку)

2022-08-15 08:19 UTC, Melekh11 commented
я понимаю что это логично и по-хорошему я должен это сделать, но совсем выбиваюсь из графика(

2022-08-19 12:59 UTC, merged